### ISSUE TITLE
Missing Paths

### ISSUE THREAD

**Issue by seadoggie01** [genius257/au3unit#1]
Your project references a path that isn't in the scope of this project, suggesting that:

- AutoIt executable should be here: <BaseDir>\au3pm\autoit\autoit3.exe
- StringRegExpSplit.au3 should be here: <BaseDir>\..\au3pm\StringRegExpSplit.au3

Also, some documentation would be awesome, because I'd love to start using this but don't know where to begin. Alternately, I'd be happy to work on documentation if you'd put a few examples in so I know where to start :D

**Comment by genius257** [comment]
Hi @seadoggie01 
The project references under the **au3pm** folder is handled by the AutoIt3 Package manager (au3pm) via the [au3pm.json](https://github.com/genius257/au3unit/blob/master/au3pm.json) file.
Currently au3pm needs au3unit to make unit tests. And au3unit needs au3pm. So my "polyfill" solution until au3pm is ready is to download the dependencies manually and extract them (a hassle i know)

the autoit folder contains the [latest autoit release](https://www.autoitscript.com/autoit3/files/archive/autoit/autoit-v3.3.14.5.zip)

the StringRegExpSplit folder contains the [latest zip download](https://github.com/genius257/StringRegExpSplit/archive/master.zip) from the master branch of my [StringRegExpSplit repo](https://github.com/genius257/StringRegExpSplit)

I made assertEquals and assertNotEquals work with arrays and correct error messages just today, so now i can start making au3pm working, if the above is too confusing, wait for my au3pm beta release soon :)

About the documentation: so far it's not ready. I can whip something up in the README.md :) but most of the code is based on the phpunit framework

**Comment by genius257** [comment]
Here's an example, showing planned usage with appveyor https://github.com/genius257/StringRegExpSplit/blob/master/appveyor.yml

Until i update the README.md, the au3pm.bat is used to test the au3unit library itself.

**Comment by seadoggie01** [comment]
Ah, I see :) I should've noticed there were no releases as well. I'm looking forward to this!
